# Implement a custom layer that performs layer normalisation

## Define the layer (inherit from keras layer class)

In [18]:
import tensorflow as tf
from tensorflow import keras

class MyDense(keras.layers.Layer):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        
    def build(self, batch_input_shape):
        self.alpha = self.add_weight(name='alpha', 
                                     shape=batch_input_shape[-1:], 
                                     dtype=tf.float32,
                                     initializer='ones')
        
        self.beta = self.add_weight(name='beta', 
                                    shape=batch_input_shape[-1:], 
                                    dtype=tf.float32,
                                    initializer='zeros')
        
    def call(self, X):
        mean, variance = tf.nn.moments(X,
                                       axes=-1,
                                       keepdims=True)
        sd = tf.math.sqrt(variance)
        
        epsilon = 0.001
        
        return tf.math.multiply(self.alpha, X - mean)/(sd + epsilon) + self.beta

In [46]:
import numpy as np

X1 = np.random.rand(1, 3).astype(np.float32)  # float 32 used by tensorflow
X2 = tf.random.uniform((1,3))
print(X1)
print(X2)

[[0.06490835 0.58166593 0.10745182]]
tf.Tensor([[0.54953444 0.9669924  0.44822013]], shape=(1, 3), dtype=float32)


In [47]:
layer = tf.keras.layers.LayerNormalization(1, input_shape=(None, 3))
print(layer.variables)

[]


In [48]:
layer_output = layer(X2)
print(layer_output)

tf.Tensor([[-0.4647863  1.3764219 -0.9116353]], shape=(1, 3), dtype=float32)


In [49]:
my_dense = MyDense(input_shape=(None, 3))
print(my_dense.variables)

[]


In [50]:
layer_output_2 = my_dense(X2)
print(layer_output_2)

tf.Tensor([[-0.46729255  1.3838441  -0.9165513 ]], shape=(1, 3), dtype=float32)
